#ifndef CONFIG_H
#define CONFIG_H

#define MODE_INDICATOR_START 23
#define MODE_ONE_INDICATOR 23
#define MODE_TWO_INDICATOR 24
#define MODE_THREE_INDICATOR 25
#define MODE_ONE_LED_START 20
#define MODE_TWO_LED_START 15
#define MODE_THREE_LED_START 11
#define MODE_STEPS_COUNT 10

#define NUMBER_OF_STARTING_LIVES 4
#define MAX_DEAD_TIME 200
#define MAX_POINTS 11
#define TIME_OF_LOOSE_ANIMATION 200
#define TIME_OF_WINNING_ANIMATION 200
#define MAX_DIFICULTY 55


#define SELECTED_DEVICE 4
#define CHARACTER_NAME "SOMA_LED"//"JORDANA" //"LAURO" // "SOMA_LED" //"ANIMUS_LED" // //"ANDREIA" //"MIGUEL"
#endif